version: 2.1

orbs:
  evals: circleci/evals@1.0
  slack: circleci/slack@4.13.2

# PIPELINE PARAMETERS
parameters:
  run-braintrust-evals:
    type: boolean
    default: false
  run-langsmith-evals:
    type: boolean
    default: false

# EXECUTORS
executors:
  python:
    docker:
      - image: cimg/python:3.11

# COMMANDS
commands:
  notify_fail_slack:
    steps:
      - slack/notify:
          channel: llmops-service-notifications
          branch_pattern: AITEAM-97_nightly-runs
          event: fail
          template: basic_fail_1

# WORKFLOWS
workflows:
  braintrust-evals:
    when: << pipeline.parameters.run-braintrust-evals >>
    jobs:
      - run-braintrust-evals:
          context:
            - ai-llm-eval-examples # Replace this with your context name
            - slack-notification-access-token # Remove this if you don't want to use Slack notifications
  langsmith-evals:
    when: << pipeline.parameters.run-langsmith-evals >>
    jobs:
      - run-langsmith-evals:
          context:
            - ai-llm-eval-examples # Replace this with your context name
            - slack-notification-access-token # Remove this if you don't want to use Slack notifications

# JOBS
jobs:
  run-braintrust-evals:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install braintrust
            pip install -r ./braintrust/requirements.txt
      - evals/eval:
          circle_pipeline_id: << pipeline.id >>
          eval_platform: braintrust
          cmd: braintrust eval braintrust/eval_tutorial.py
      - run:
          name: notify slack temp
          command: |
            exit 1
      - notify_fail_slack

  run-langsmith-evals:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -r ./langsmith/requirements.txt
      - evals/eval:
          circle_pipeline_id: << pipeline.id >>
          cmd: python3 langsmith/eval.py
          eval_platform: langsmith
      - notify_fail_slack
